### ISSUE TITLE
能不能更新offsets

### ISSUE THREAD

**Issue by 2063669460** [Mzzzj/CS2_DMA_Extrnal#14]

**Comment by 2063669460** [comment]
还有client.dll.json

**Comment by 2063669460** [comment]
![image](https://github.com/Mzzzj/CS2_DMA_Extrnal/assets/115350608/c82d1765-cc38-4ab1-8348-e3a0e005334b)

**Comment by 2063669460** [comment]
咋回事

**Comment by Mzzzj** [comment]
此项目不再维护，想要正常运行你需要自己学会更新偏移文件。你可以去这个论坛学习如何自己更新偏移文件，https://www.unknowncheats.me/forum/counter-strike-2-a/576077-counter-strike-2-reversal-structs-offsets.html 我不会教你们，你们需要自己去学习

This project is no longer maintained, and in order to run properly, you need to learn how to update offset files yourself. You can go to this forum to learn how to update offset files yourself, https://www.unknowncheats.me/forum/counter-strike-2-a/576077-counter-strike-2-reversal-structs-offsets.html I won't teach you, you need to learn on your own
