### ISSUE TITLE
现在还能正常使用吗

### ISSUE THREAD

**Issue by 2063669460** [Mzzzj/CS2_DMA_Extrnal#15]
现在还能正常使用吗

_Originally posted by @Accel1337 in https://github.com/Mzzzj/CS2_DMA_Extrnal/issues/9#issuecomment-2051922512_
            不可以了，他这个偏移没怎么看懂，不知道怎么更新基址

**Comment by Mzzzj** [comment]
此项目不再维护，想要正常运行你需要自己学会更新偏移文件。你可以去这个论坛学习如何自己更新偏移文件，https://www.unknowncheats.me/forum/counter-strike-2-a/576077-counter-strike-2-reversal-structs-offsets.html 我不会教你们，你们需要自己去学习

This project is no longer maintained, and in order to run properly, you need to learn how to update offset files yourself. You can go to this forum to learn how to update offset files yourself, https://www.unknowncheats.me/forum/counter-strike-2-a/576077-counter-strike-2-reversal-structs-offsets.html I won't teach you, you need to learn on your own
